# FeatherDonationEvent | Event/Commands for buycraft use as well as donor display settings

#Should the donor head display(s) be updated only once per day after a restart?
change-display-once-per-day: false

#Should the donor head display(s) be updated on a delay?
change-display-on-interval: false
# If the above is set to true, how long should the display update delay be?
minute-delay: 240

# Randomized Donor display(s)
general:
  1:
    stand: [ 0,0,0 ]
    sign: [ 0,0,0 ]
  2:
    stand: [ 0,0,0 ]
    sign: [ 0,0,0 ]
  3:
    stand: [ 0,0,0 ]
    sign: [ 0,0,0 ]

# Newest Donor display
newest:
  stand: [ 0,0,0 ]
  sign: [ 0,0,0 ]

messages:
  general-display-updated: "<white>• <#656b96>Donor display updated. | <#949bd1><donors>"
  no-command-permission: "<#656b96>You don't have permission to use that command."